FROM tensorflow/tensorflow:2.11.0

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY ./src /app

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
